version: '3.3'
services:
  data:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '1q2w3e4r'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'datauser'
      MYSQL_PASSWORD: 'password'
    restart: always
    volumes:
     - db_data:/var/lib/mysql
  app:
    links:
      - data
    build: ./
    ports:
      - "80:80"
      - "443:443"
volumes:
   db_data: {}